version: '2.2'
services:
  sqs:
    image: 'motoserver/moto'
    entrypoint: moto_server
    ports:
      - 4567:4567
    command:
      - sqs
      - -p
      - "4567"
      - -H
      - 0.0.0.0
  ruby:
    build:
      dockerfile: ruby.Dockerfile
      context: .
    volumes:
      - "$PWD:/app:ro,cached"
    environment:
      GEM_PATH: "vendor/bundle/ruby/2.5.0"
    working_dir: /app
    entrypoint: ruby
    command:
      - -e
      - "puts 'Welcome to your service.'"
  vendor:
    extends: ruby
    volumes:
      - "$PWD:/app:delegated"
      - "$PWD/vendor:/vendor:delegated"
      - "$PWD/Gemfile:/Gemfile"
    entrypoint: sh
    command:
      - -c
      - "echo 'INFO: Vendoring dependencies...' && bundle install --path /vendor/bundle"
  vendor-with-test:
    extends: ruby
    volumes:
      - "$PWD:/app:delegated"
      - "$PWD/vendor:/vendor:delegated"
      - "$PWD/Gemfile:/Gemfile"
    entrypoint: sh
    command:
      - -c
      - "echo 'INFO: Vendoring dependencies...' && bundle install --with test --path /vendor/bundle"
  parking-bot:
    extends: ruby
    command: bin/parking_bot.rb
  unit:
    extends: ruby
    entrypoint: vendor/bundle/ruby/2.5.0/bin/rspec
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
      AWS_SQS_ENDPOINT_URL: "http://sqs:4567"
      AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb:8000"
      ENVIRONMENT: test
    command:
      - --tag
      - unit
      - --tag
      - unit_with_database
      - --tag
      - unit_with_queue
      - --fail-fast
      - --format
      - documentation
  lint:
    extends: ruby
    entrypoint: vendor/bundle/ruby/2.5.0/bin/rubocop
    volumes:
      - "$PWD:/app:delegated" # need write access so that we can auto-correct
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
      AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb:8000"
      ENVIRONMENT: test
    command:
      - --auto-correct
      - --except
      - Style/Documentation,Style/GlobalVars
      - lib/**/*.rb
      - spec
