version: '2.2'
services:
  moto:
    image: 'motoserver/moto'
    entrypoint: moto_server
  sqs:
    extends: moto
    ports:
      - 4567:4567
    command:
      - sqs
      - -p
      - "4567"
      - -H
      - 0.0.0.0
  ruby:
    build:
      dockerfile: ruby.Dockerfile
      context: .
    environment:
      VERIFY_CODE_QUEUE_NAME: "ppprk_verification_codes"
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    entrypoint: ruby
    command:
      - -e
      - "puts 'Welcome to your service.'"
  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      ENVIRONMENT: test
    volumes:
      - /dev/shm:/dev/shm
      - $PWD:/app:cached,ro
    working_dir: /app
    ports:
      - 4444:4444
      - 5900:5900
  parking-bot:
    extends: ruby
    env_file: .env
    command: bin/parking_bot.rb
  unit:
    extends: ruby
    entrypoint: rspec
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
      AWS_SQS_ENDPOINT_URL: "http://sqs:4567"
      AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb:8000"
      ENVIRONMENT: test
    command:
      - --tag
      - unit
      - --fail-fast
      - --format
      - documentation
  integration:
    extends: ruby
    entrypoint: rspec
    env_file: .env
    environment:
      LOAD_PATH: "/app/spec/integration;/app/spec"
    command:
      - --tag
      - integration_local
      - --fail-fast
      - --format
      - documentation
  check_environment:
    extends: ruby
    entrypoint: rspec
    env_file: .env
    environment:
      LOAD_PATH: "/app/spec/environment;/app/spec"
    command:
      - --tag
      - env_check
      - --fail-fast
      - --format
      - documentation
  unit_page: # Use this for testing web page transitions.
    extends: ruby
    entrypoint: rspec
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
      AWS_SQS_ENDPOINT_URL: "http://sqs:4567"
      AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb:8000"
      ENVIRONMENT: test
    command:
      - --tag
      - unit_page
      - --fail-fast
      - --format
      - documentation
  lint:
    extends: ruby
    entrypoint: rubocop
    volumes:
      - "$PWD:/app:delegated" # need write access so that we can auto-correct
    environment:
      LOAD_PATH: "/app/spec/unit;/app/spec;/app/lib"
      AWS_DYNAMODB_ENDPOINT_URL: "http://dynamodb:8000"
      ENVIRONMENT: test
    command:
      - --auto-correct
      - --except
      - Style/Documentation,Style/GlobalVars
      - lib/**/*.rb
      - spec
