---
name: Scheduled parking payments
on:
  schedule:
    - cron: "*/5 * * * *"

# Apologies for the violation of DRY here. GitHub Actions didn't support
# reusable steps (unless you wanted to write JavaScript to do it, which...no).
jobs:
  pay_for_parking_scheduled:
    name: Pay for parking per a schedule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Docker Compose
        run: curl -L ${DOCKER_COMPOSE_URL}/docker-compose-`uname -s`-`uname -m` > ./docker-compose &&
             chmod +x ./docker-compose
        env:
          DOCKER_COMPOSE_URL: https://github.com/docker/compose/releases/download/1.22.0

      - name: Decrypt environment file
        run: ./docker-compose -f docker-compose.ci.yml run --rm decrypt-env
        env:
          ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}

      - name: Check for and download run file
        run: ./docker-compose -f docker-compose.deploy.yml run --rm aws s3 cp s3://${{ secrets.queue_bucket }}/ppprk_run_file || true

      - name: Stop if run file wasn't downloaded
        run: if [ ! -f ppprk_run_file ];
             then
               echo "::error No run file found. Halting.";
               echo "::set-env name=scheduled_parking_file_found::1";
               echo "::set-env name=continue_parking::1";
             else
               echo "::set-env name=scheduled_parking_file_found::0";
             fi

      - name: Check if current time exceeds desired time to park (if scheduled)
        if: env.scheduled_parking_file_found == 0
        run: current_time=$(date +%s); 
             desired_time=$(cat ppprk_run_file | 
                egrep '^TIME_TO_SCHEDULE_PARKING=' | 
                cut -f2 -d '='); 
             if [ "$current_time" -lt "$desired_time" ];
             then
               echo "::error We're scheduled to run at $(date -d $desired_time), but it's $(date -d $current_time). Halting until go time.";
               echo "::set-env name=continue_parking::1";
             fi

        # The next few steps should only execute if a scheduled run was found
        # or if we were told to execute per the 'execute' webhook.
      - name: Deploy AWS infrastructure
        if: env.continue_parking == 0
        run: ./docker-compose -f docker-compose.deploy.yml run --rm terraform apply

      - name: Run Parking Bot at a scheduled time (if scheduled)
        if: env.continue_parking == 0
        run: ./docker-compose up -d selenium && 
              zone_number=$(cat ppprk_run_file | egrep '^ZONE=' | cut -f2 -d '=') && 
              space_number=$(cat ppprk_run_file | egrep '^SPACE=' | cut -f2 -d '=') && 
              docker-compose run --rm -e ZONE_NUMBER=$zone_number -e SPACE_NUMBER=$space_number parking_bot

      - name: Turn everything down
        if: env.continue_parking == 0
        run: ./docker-compose down

      - name: Delete parking run from queue bucket
        if: env.continue_parking == 0
        run: ./docker-compose run --rm aws s3 rm s3://${{ secrets.queue_bucket }}/ppprk_run_file

      - name: Purge the queue when done
        if: env.continue_parking == 0
        run: ./docker-compose -f docker-compose.deploy.yml run --rm purge_verification_codes_queue
